In [22]:
from google.colab import files
uploaded = files.upload()

Saving superstore.csv to superstore (1).csv

In [12]:
df = pd.read_csv('superstore.csv')
df.head()

,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,sales,quantity,discount,profit
0,Second Class,Consumer,United States,Los Angeles,California,90036,West,Technology,Phones,859.99,2,0.00,238.98
1,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.57,3,0.45,-383.03
2,First Class,Corporate,United States,New York City,New York,10024,East,Office Supplies,Binders,119.98,4,0.20,23.98
3,Same Day,Home Office,United States,Seattle,Washington,98103,West,Technology,Copiers,959.98,1,0.00,335.99
4,Standard Class,Consumer,United States,Chicago,Illinois,60601,Central,Furniture,Chairs,731.94,3,0.20,36.60

In [16]:
df.groupby('category')[['sales', 'profit']].sum().sort_values('sales', ascending = False)

                    sales   profit
category
Technology       16819.80  5514.82
Furniture        10823.35 -2487.57
Office Supplies   1213.78   371.01

In [17]:
region_summary = df.groupby('region')[['sales','profit']].sum()
region_summary['profit_status'] = region_summary['profit'].apply(lambda x: 'Loss' if x < 0 else 'Profit')
region_summary.sort_values('profit')

            sales   profit profit_status
region
East      2093.85  -464.17          Loss
West     11168.69  1065.42        Profit
South     6122.46  1171.87        Profit
Central   9471.93  1625.14        Profit

In [18]:
def discount_level(discount):
    if discount == 0:
        return 'No Discount'
    elif discount <= 0.20:
        return 'Low Discount'
    else:
        return 'High Discount'

df['discount_level'] = df['discount'].apply(discount_level)
df.groupby('discount_level').agg(total_orders=('discount','count'), avg_profit=('profit','mean'), total_profit=('profit','sum')).sort_values('avg_profit', ascending=False)

                total_orders  avg_profit  total_profit
discount_level
No Discount               27  204.700000       5526.90
Low Discount              12   69.208333        830.50
High Discount             11 -269.012727      -2959.14

In [19]:
subcat_profit = df.groupby('sub_category')['profit'].sum()
subcat_profit[subcat_profit < 0].sort_values()

sub_category
Tables      -2425.03
Bookcases    -534.11
Name: profit, dtype: float64

In [20]:
def customer_value(profit):
    if profit >= 90:
        return 'High Value'
    elif profit >= 50:
        return 'Average Value'
    else:
        return 'Low Value'

segment_summary = df.groupby('segment').agg(
    total_sales=('sales','sum'),
    avg_order_value=('sales','mean'),
    avg_profit_per_order=('profit','mean')
)
segment_summary['customer_value'] = segment_summary['avg_profit_per_order'].apply(customer_value)
segment_summary.sort_values('avg_profit_per_order', ascending=False)

             total_sales  avg_order_value  avg_profit_per_order customer_value
segment
Corporate        8063.92       537.594667            118.905333     High Value
Home Office      8138.81       626.062308             64.290769  Average Value
Consumer        12654.20       575.190909             35.404545      Low Value

In [21]:
df.groupby('ship_mode').agg(
    total_orders=('ship_mode','count'),
    avg_order_value=('sales','mean')
).sort_values('total_orders', ascending=False)

                total_orders  avg_order_value
ship_mode
Standard Class            15       555.886667
First Class               14       692.490714
Second Class              14       472.772857
Same Day                   7       600.705714